"""init

Revision ID: 012676617ef4
Revises: 
Create Date: 2025-02-03 14:48:02.879139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012676617ef4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('deadline', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Events')
    # ### end Alembic commands ###
