"""init

Revision ID: 3a24d0bd7072
Revises: 
Create Date: 2025-02-04 02:29:43.567290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a24d0bd7072'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bets',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('sum_bet', sa.Numeric(precision=100, scale=2), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='eventstatus'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bets')
    # ### end Alembic commands ###
