"""init

Revision ID: d188a6ed4b7d
Revises: 
Create Date: 2025-02-03 17:46:52.555985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd188a6ed4b7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bets',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sum_bet', sa.Numeric(precision=100, scale=2), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'FINISHED_WIN', 'FINISHED_LOSE', name='eventstatus'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bets')
    # ### end Alembic commands ###
